spring:  
  r2dbc:
    url: r2dbc:mysql://localhost:3306/javatutos
    username: app_user
    password: "PanFz$6d"
    
  flyway:
    url: jdbc:mysql://localhost:3306/javatutos 
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    
app:
  guest:
    username: guest
    password: la1LmJz?