spring:
  application:
    name: spring-reactive-skillrater
  profiles:
    default: dev

resilience4j.ratelimiter:
  instances:
    publicVoteLimiter:
      limit-for-period: 10              # Allow 10 votes per refresh period per IP
      limit-refresh-period: 10s         # Reset window every 10s
      timeout-duration: 0               # No waiting — fail fast if limit reached
      register-health-indicator: true

logging:
  file:
    path: /home/nklinux/Documents/workspace/projects/skillrater/logs
  level:
    root: INFO
    reactor: WARN
    org.springframework.web: INFO
    nk.springprojects.reactive: INFO
  logback:
    rollingpolicy:
      file-name-pattern: app-%d{yyyy-MM-dd}.log
      max-file-size: 10MB
      max-history: 7

server:
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-message: ALWAYS
    include-stacktrace: ALWAYS

app:
  guest:
    username: guest
    password: la1LmJz?