spring:
  application:
    name: spring-reactive-skillrater
  profiles:
    default: dev
    
    
server:
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-message: ALWAYS
    include-stacktrace: ALWAYS