name: Build and Deploy application container
on:
  push:
   branches:
      - main

jobs:
  build:
    name: Maven Build phase
    runs-on: Ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: javatutos
          MYSQL_ROOT_PASSWORD: thedba
        ports:
          - 3306:3306
    steps:
      - name: checkout the branch
        uses: actions/checkout@v3
      - name: setup java build tools
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: compile and build the spring boot code
        run: |
          echo "Clea, Compile, and package the Jar" && \
          mvn clean install package -P test -Dspring.r2dbc.username=root 
    
    
